### PR TITLE
Stripebot 890 chore centralize query validation

### LINKED ISSUE #890: Input Sanitization & Normalization
Before sending text to an AI model, you must ensure the data is "clean." If a user enters 5,000 words or just empty spaces, it could crash your API call or waste your token quota.

To-Do:

[ ] Create a validateQuery helper to trim whitespace and check for empty strings.
[ ] Implement a length check (e.g., if the query is > 1000 characters, truncate it or return an error).
[ ] (Optional) Convert the text to lowercase to keep the input consistent with your ingestion style.

### PR DESCRIPTION
**Pull request by mushkan27**
## Summary

- Added a centralized query validation utility in `src/utils/validateQuery.js` to normalize prompt handling in one place.
- Updated chat flow to use shared validation in both `src/controllers/chat.controller.js` and `src/services/gemini.service.js` to avoid duplicate trim/empty checks.
- Extended API constants in `src/constants/apiResponse.js` with `QUERY_TOO_LONG` messaging for oversized prompt handling.

**Linked issues:** Closes #890 

## Summary by CodeRabbit

* **New Features**
  * Implemented query length validation with a maximum limit of 1,000 characters per prompt. Users receive standardized error messages when queries exceed the allowed length.

* **Refactor**
  * Consolidated prompt validation logic across core services to ensure consistent error handling and uniform response behavior.

### CODE REVIEW

**Comment by mushkan27** [comment]
@coderabbitai review

File: PBL4/StripeBot/backend/src/utils/validateQuery.js [hunk 1]
```diff
@@ -0,0 +1,48 @@
...
+ * - Trims whitespace
+ * - Rejects empty query
+ * - Enforces max length (throws by default)
+ *
+ * Parameters:
+ * - input: The user query string to validate
+ * - options: An object with optional settings:
+ *   - maxLength: The maximum length of the query (default: DEFAULT_MAX_QUERY_LENGTH)
+ */
+function validateQuery(input, { maxLength = DEFAULT_MAX_QUERY_LENGTH } = {}) {
```
Comment (rajutamanglama63) [inline PBL4/StripeBot/backend/src/utils/validateQuery.js]: Consider making the parameter more easy to understand.
e.g:
```
function validateQuery(input, options = {}) {
  const maxLength = options.maxLength ?? DEFAULT_MAX_QUERY_LENGTH;
  // ... rest uses maxLength
}
```

**Review by rajutamanglama63 — COMMENTED** [review]
lgtm! one comment to follow.

File: PBL4/StripeBot/backend/src/utils/validateQuery.js (hunk 1 above)
Comment (mushkan27) [reply PBL4/StripeBot/backend/src/utils/validateQuery.js]: Done

**Review by mushkan27 — COMMENTED** [review]
applied requested changes from PR review

**Review by rajutamanglama63 — APPROVED** [review]
lgtm!
